var wms_layers = [];

var format_Parceles_RdC_0 = new ol.format.GeoJSON();
var features_Parceles_RdC_0 = format_Parceles_RdC_0.readFeatures(json_Parceles_RdC_0, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Parceles_RdC_0 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Parceles_RdC_0.addFeatures(features_Parceles_RdC_0);
var lyr_Parceles_RdC_0 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Parceles_RdC_0, 
                style: style_Parceles_RdC_0,
                popuplayertitle: 'Parceles_RdC',
                interactive: false,
                title: '<img src="styles/legend/Parceles_RdC_0.png" /> Parceles_RdC'
            });
var format_Buidings_RdC__1 = new ol.format.GeoJSON();
var features_Buidings_RdC__1 = format_Buidings_RdC__1.readFeatures(json_Buidings_RdC__1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Buidings_RdC__1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Buidings_RdC__1.addFeatures(features_Buidings_RdC__1);
var lyr_Buidings_RdC__1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Buidings_RdC__1, 
                style: style_Buidings_RdC__1,
                popuplayertitle: 'Buidings_RdC_',
                interactive: true,
    title: 'Buidings_RdC_<br />\
    <img src="styles/legend/Buidings_RdC__1_0.png" /> Teulades sense amiant<br />\
    <img src="styles/legend/Buidings_RdC__1_1.png" /> Teulades amb amiant<br />' });
var format_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2 = new ol.format.GeoJSON();
var features_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2 = format_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2.readFeatures(json_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2.addFeatures(features_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2);
var lyr_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2, 
                style: style_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2,
                popuplayertitle: 'RieraDeCaldes — limits_administratius_icgc_rieradecaldes',
                interactive: false,
                title: '<img src="styles/legend/RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2.png" /> RieraDeCaldes — limits_administratius_icgc_rieradecaldes'
            });

lyr_Parceles_RdC_0.setVisible(true);lyr_Buidings_RdC__1.setVisible(true);lyr_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2.setVisible(true);
var layersList = [lyr_Parceles_RdC_0,lyr_Buidings_RdC__1,lyr_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2];
lyr_Parceles_RdC_0.set('fieldAliases', {'fid': 'fid', 'gml_id': 'gml_id', 'areaValue': 'areaValue', 'areaValue_uom': 'areaValue_uom', 'beginLifespanVersion': 'beginLifespanVersion', 'endLifespanVersion': 'endLifespanVersion', 'localId': 'localId', 'namespace': 'namespace', 'label': 'label', 'nationalCadastralReference': 'nationalCadastralReference', 'pos': 'pos', 'layer': 'layer', 'path': 'path', });
lyr_Buidings_RdC__1.set('fieldAliases', {'fid': 'fid', 'gml_id': 'gml_id', 'lowerCorner': 'lowerCorner', 'upperCorner': 'upperCorner', 'beginLifespanVersion': 'beginLifespanVersion', 'conditionOfConstruction': 'Estat de la construcció', 'beginning': 'beginning', 'end': 'end', 'endLifespanVersion': 'endLifespanVersion', 'informationSystem': 'informationSystem', 'reference': 'Referència', 'localId': 'localId', 'namespace': 'namespace', 'horizontalGeometryEstimatedAccuracy': 'horizontalGeometryEstimatedAccuracy', 'horizontalGeometryEstimatedAccuracy_uom': 'horizontalGeometryEstimatedAccuracy_uom', 'horizontalGeometryReference': 'horizontalGeometryReference', 'referenceGeometry': 'referenceGeometry', 'currentUse': 'Ús habitual', 'numberOfBuildingUnits': 'Nombre d\'unitats construïdes dins l\'edifici', 'numberOfDwellings': 'Nombre d\'habitatges', 'numberOfFloorsAboveGround': 'numberOfFloorsAboveGround', 'documentLink': 'documentLink', 'format': 'format', 'sourceStatus': 'sourceStatus', 'officialAreaReference': 'officialAreaReference', 'value': 'value', 'value_uom': 'value_uom', 'layer': 'layer', 'path': 'path', 'Amiant': 'Amiant', 'Taula_amiant_id': 'Taula_amiant_id', 'Taula_amiant_CODIMUNI': 'Taula_amiant_CODIMUNI', 'Taula_amiant_NOMMUNI': 'Nom del municipi', 'Taula_amiant_adreça': 'Adreça', 'Taula_amiant_data_detec': 'Taula_amiant_data_detec', 'Taula_amiant_tipus_id': 'Taula_amiant_tipus_id', 'Taula_amiant_metode_det': 'Taula_amiant_metode_det', 'Taula_amiant_origen_id': 'Taula_amiant_origen_id', 'Taula_amiant_geometria_m2': 'Taula_amiant_geometria_m2', 'Taula_amiant_pes_estimat_Kg': 'Taula_amiant_pes_estimat_Kg', 'Taula_amiant_m²': 'Taula_amiant_m²', 'Taula_amiant_Pes en kg': 'Pes de l\'amiant en Kg', 'Taula_amiant_Dimensió en m²': 'Dimensió de l\'amiant en m²', 'Taula_amiant_Nombre d\'elements amb amiant': 'Nombre d\'elements amb amiant', });
lyr_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2.set('fieldAliases', {'fid': 'fid', 'codi_ine': 'codi_ine', 'codi_municipi': 'codi_municipi', 'nom_municipi': 'nom_municipi', 'codi_comarca': 'codi_comarca', 'nom_comarca': 'nom_comarca', 'cap_comarca': 'cap_comarca', 'codi_vegueria': 'codi_vegueria', 'nom_vegueria': 'nom_vegueria', 'cap_vegueria': 'cap_vegueria', 'codi_provincia': 'codi_provincia', 'nom_provincia': 'nom_provincia', 'cap_provincia': 'cap_provincia', 'area_km': 'area_km', 'altitud_metres': 'altitud_metres', 'pob_dones_24': 'pob_dones_24', 'pob_homes_24': 'pob_homes_24', 'pob_total_24': 'pob_total_24', 'edat_mitjana_24': 'edat_mitjana_24', 'per_pob_menys16_24': 'per_pob_menys16_24', 'per_pob_mes64_24': 'per_pob_mes64_24', 'tamany_mitja_llar_22': 'tamany_mitja_llar_22', 'per_pob_espanyola_22': 'per_pob_espanyola_22', 'per_pob_extranjera_22': 'per_pob_extranjera_22', 'renda_neta_mitjana_persona_22': 'renda_neta_mitjana_persona_22', 'renda_neta_mitjana_llar_22': 'renda_neta_mitjana_llar_22', 'renda_bruta_mitjana_persona_22': 'renda_bruta_mitjana_persona_22', 'renda_bruta_mitjana_persona_21': 'renda_bruta_mitjana_persona_21', 'per_dif_renda_bruta_mitjana_persona_22_22': 'per_dif_renda_bruta_mitjana_persona_22_22', 'renda_bruta_mitjana_llar_22': 'renda_bruta_mitjana_llar_22', 'nombre_rebuts_ibi_22': 'nombre_rebuts_ibi_22', 'quota_integra_ibi_22': 'quota_integra_ibi_22', 'parc_vehicles_total_22': 'parc_vehicles_total_22', 'residus_kg_hab_dia_21': 'residus_kg_hab_dia_21', 'codi_ine_red': 'codi_ine_red', 'datos_para_mapa_municipios_Municipi': 'datos_para_mapa_municipios_Municipi', 'datos_para_mapa_municipios_Incremento_Anual_Pct': 'datos_para_mapa_municipios_Incremento_Anual_Pct', 'datos_para_mapa_municipios_Significativo': 'datos_para_mapa_municipios_Significativo', 'datos_para_mapa_municipios_P_Valor': 'datos_para_mapa_municipios_P_Valor', 'datos_para_mapa_municipios_Latitut': 'datos_para_mapa_municipios_Latitut', 'datos_para_mapa_municipios_Longitut': 'datos_para_mapa_municipios_Longitut', });
lyr_Parceles_RdC_0.set('fieldImages', {'fid': 'TextEdit', 'gml_id': 'TextEdit', 'areaValue': 'Range', 'areaValue_uom': 'TextEdit', 'beginLifespanVersion': 'DateTime', 'endLifespanVersion': 'TextEdit', 'localId': 'TextEdit', 'namespace': 'TextEdit', 'label': 'TextEdit', 'nationalCadastralReference': 'TextEdit', 'pos': 'TextEdit', 'layer': 'TextEdit', 'path': 'TextEdit', });
lyr_Buidings_RdC__1.set('fieldImages', {'fid': 'TextEdit', 'gml_id': 'TextEdit', 'lowerCorner': 'TextEdit', 'upperCorner': 'TextEdit', 'beginLifespanVersion': 'DateTime', 'conditionOfConstruction': 'TextEdit', 'beginning': 'TextEdit', 'end': 'TextEdit', 'endLifespanVersion': 'TextEdit', 'informationSystem': 'TextEdit', 'reference': 'TextEdit', 'localId': 'TextEdit', 'namespace': 'TextEdit', 'horizontalGeometryEstimatedAccuracy': 'TextEdit', 'horizontalGeometryEstimatedAccuracy_uom': 'TextEdit', 'horizontalGeometryReference': 'TextEdit', 'referenceGeometry': 'CheckBox', 'currentUse': 'TextEdit', 'numberOfBuildingUnits': 'Range', 'numberOfDwellings': 'Range', 'numberOfFloorsAboveGround': 'TextEdit', 'documentLink': 'TextEdit', 'format': 'TextEdit', 'sourceStatus': 'TextEdit', 'officialAreaReference': 'TextEdit', 'value': 'Range', 'value_uom': 'TextEdit', 'layer': 'TextEdit', 'path': 'TextEdit', 'Amiant': 'Range', 'Taula_amiant_id': 'TextEdit', 'Taula_amiant_CODIMUNI': 'TextEdit', 'Taula_amiant_NOMMUNI': 'TextEdit', 'Taula_amiant_adreça': 'TextEdit', 'Taula_amiant_data_detec': 'TextEdit', 'Taula_amiant_tipus_id': 'TextEdit', 'Taula_amiant_metode_det': 'TextEdit', 'Taula_amiant_origen_id': 'TextEdit', 'Taula_amiant_geometria_m2': 'TextEdit', 'Taula_amiant_pes_estimat_Kg': 'TextEdit', 'Taula_amiant_m²': 'TextEdit', 'Taula_amiant_Pes en kg': 'TextEdit', 'Taula_amiant_Dimensió en m²': 'TextEdit', 'Taula_amiant_Nombre d\'elements amb amiant': 'TextEdit', });
lyr_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2.set('fieldImages', {'fid': 'TextEdit', 'codi_ine': 'TextEdit', 'codi_municipi': 'TextEdit', 'nom_municipi': 'TextEdit', 'codi_comarca': 'TextEdit', 'nom_comarca': 'TextEdit', 'cap_comarca': 'TextEdit', 'codi_vegueria': 'TextEdit', 'nom_vegueria': 'TextEdit', 'cap_vegueria': 'TextEdit', 'codi_provincia': 'TextEdit', 'nom_provincia': 'TextEdit', 'cap_provincia': 'TextEdit', 'area_km': 'TextEdit', 'altitud_metres': 'Range', 'pob_dones_24': 'Range', 'pob_homes_24': 'Range', 'pob_total_24': 'Range', 'edat_mitjana_24': 'TextEdit', 'per_pob_menys16_24': 'TextEdit', 'per_pob_mes64_24': 'TextEdit', 'tamany_mitja_llar_22': 'TextEdit', 'per_pob_espanyola_22': 'TextEdit', 'per_pob_extranjera_22': 'TextEdit', 'renda_neta_mitjana_persona_22': 'Range', 'renda_neta_mitjana_llar_22': 'Range', 'renda_bruta_mitjana_persona_22': 'Range', 'renda_bruta_mitjana_persona_21': 'Range', 'per_dif_renda_bruta_mitjana_persona_22_22': 'TextEdit', 'renda_bruta_mitjana_llar_22': 'Range', 'nombre_rebuts_ibi_22': 'Range', 'quota_integra_ibi_22': 'Range', 'parc_vehicles_total_22': 'Range', 'residus_kg_hab_dia_21': 'TextEdit', 'codi_ine_red': 'Range', 'datos_para_mapa_municipios_Municipi': 'TextEdit', 'datos_para_mapa_municipios_Incremento_Anual_Pct': 'TextEdit', 'datos_para_mapa_municipios_Significativo': 'TextEdit', 'datos_para_mapa_municipios_P_Valor': 'TextEdit', 'datos_para_mapa_municipios_Latitut': 'TextEdit', 'datos_para_mapa_municipios_Longitut': 'TextEdit', });
lyr_Parceles_RdC_0.set('fieldLabels', {'fid': 'no label', 'gml_id': 'no label', 'areaValue': 'no label', 'areaValue_uom': 'no label', 'beginLifespanVersion': 'no label', 'endLifespanVersion': 'no label', 'localId': 'no label', 'namespace': 'no label', 'label': 'no label', 'nationalCadastralReference': 'no label', 'pos': 'no label', 'layer': 'no label', 'path': 'no label', });
lyr_Buidings_RdC__1.set('fieldLabels', {'fid': 'hidden field', 'gml_id': 'hidden field', 'lowerCorner': 'hidden field', 'upperCorner': 'hidden field', 'beginLifespanVersion': 'hidden field', 'conditionOfConstruction': 'inline label - visible with data', 'beginning': 'hidden field', 'end': 'hidden field', 'endLifespanVersion': 'hidden field', 'informationSystem': 'hidden field', 'reference': 'inline label - always visible', 'localId': 'hidden field', 'namespace': 'hidden field', 'horizontalGeometryEstimatedAccuracy': 'hidden field', 'horizontalGeometryEstimatedAccuracy_uom': 'hidden field', 'horizontalGeometryReference': 'hidden field', 'referenceGeometry': 'hidden field', 'currentUse': 'inline label - visible with data', 'numberOfBuildingUnits': 'inline label - visible with data', 'numberOfDwellings': 'inline label - visible with data', 'numberOfFloorsAboveGround': 'hidden field', 'documentLink': 'hidden field', 'format': 'hidden field', 'sourceStatus': 'hidden field', 'officialAreaReference': 'hidden field', 'value': 'hidden field', 'value_uom': 'hidden field', 'layer': 'hidden field', 'path': 'hidden field', 'Amiant': 'hidden field', 'Taula_amiant_id': 'hidden field', 'Taula_amiant_CODIMUNI': 'hidden field', 'Taula_amiant_NOMMUNI': 'inline label - always visible', 'Taula_amiant_adreça': 'inline label - always visible', 'Taula_amiant_data_detec': 'hidden field', 'Taula_amiant_tipus_id': 'hidden field', 'Taula_amiant_metode_det': 'hidden field', 'Taula_amiant_origen_id': 'hidden field', 'Taula_amiant_geometria_m2': 'hidden field', 'Taula_amiant_pes_estimat_Kg': 'hidden field', 'Taula_amiant_m²': 'hidden field', 'Taula_amiant_Pes en kg': 'inline label - always visible', 'Taula_amiant_Dimensió en m²': 'inline label - always visible', 'Taula_amiant_Nombre d\'elements amb amiant': 'inline label - visible with data', });
lyr_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2.set('fieldLabels', {'fid': 'hidden field', 'codi_ine': 'hidden field', 'codi_municipi': 'hidden field', 'nom_municipi': 'hidden field', 'codi_comarca': 'hidden field', 'nom_comarca': 'hidden field', 'cap_comarca': 'no label', 'codi_vegueria': 'no label', 'nom_vegueria': 'no label', 'cap_vegueria': 'no label', 'codi_provincia': 'no label', 'nom_provincia': 'no label', 'cap_provincia': 'no label', 'area_km': 'no label', 'altitud_metres': 'no label', 'pob_dones_24': 'no label', 'pob_homes_24': 'no label', 'pob_total_24': 'no label', 'edat_mitjana_24': 'no label', 'per_pob_menys16_24': 'no label', 'per_pob_mes64_24': 'no label', 'tamany_mitja_llar_22': 'no label', 'per_pob_espanyola_22': 'no label', 'per_pob_extranjera_22': 'no label', 'renda_neta_mitjana_persona_22': 'no label', 'renda_neta_mitjana_llar_22': 'no label', 'renda_bruta_mitjana_persona_22': 'no label', 'renda_bruta_mitjana_persona_21': 'no label', 'per_dif_renda_bruta_mitjana_persona_22_22': 'no label', 'renda_bruta_mitjana_llar_22': 'no label', 'nombre_rebuts_ibi_22': 'no label', 'quota_integra_ibi_22': 'no label', 'parc_vehicles_total_22': 'no label', 'residus_kg_hab_dia_21': 'no label', 'codi_ine_red': 'no label', 'datos_para_mapa_municipios_Municipi': 'no label', 'datos_para_mapa_municipios_Incremento_Anual_Pct': 'no label', 'datos_para_mapa_municipios_Significativo': 'no label', 'datos_para_mapa_municipios_P_Valor': 'no label', 'datos_para_mapa_municipios_Latitut': 'no label', 'datos_para_mapa_municipios_Longitut': 'no label', });
lyr_RieraDeCaldeslimits_administratius_icgc_rieradecaldes_2.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});